spring:
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate:
      type: trace
      stat: debug
      orm.jdbc.bind: trace
